// ── DATA: Alabama Course of Study K–2 Milestones ──
// Sourced from Alabama COS ELA (2021) and Math (2019)
const MILESTONES = [

  // ═══ KINDERGARTEN ═══

  // ELA — Oral Language
  {id:'K.1',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Actively listen and take turns speaking during discussions, carrying on a conversation through multiple exchanges.',
   code:'K.1',tag:'Oral Language'},
  {id:'K.4',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Ask and answer questions to seek help, get information, or clarify information — using who, what, where, when, why, how.',
   code:'K.4',tag:'Oral Language'},
  {id:'K.5b',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Describe people, places, things, and events with relevant details in a story with three to five events.',
   code:'K.5.b',tag:'Oral Language'},

  // ELA — Concepts of Print
  {id:'K.8',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Demonstrate understanding of print — books have a cover, author, illustrator; print moves left to right, top to bottom.',
   code:'K.8',tag:'Concepts of Print'},
  {id:'K.8c',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Track print moving left to right and top to bottom; return to the beginning of the next line.',
   code:'K.8.c',tag:'Concepts of Print'},
  {id:'K.8f',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Distinguish between individual letters and words within sentences.',
   code:'K.8.f',tag:'Concepts of Print'},

  // ELA — Phonological Awareness
  {id:'K.9c',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Recognize and produce pairs of rhyming words; distinguish rhyming from non-rhyming pairs.',
   code:'K.9.c',tag:'Phonological Awareness'},
  {id:'K.9d',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Count, blend, and segment syllables in spoken words, including compound words.',
   code:'K.9.d',tag:'Phonological Awareness'},
  {id:'K.9g',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Blend and segment phonemes in single-syllable spoken words of 3–4 phonemes (e.g., c-a-t → "cat").',
   code:'K.9.g',tag:'Phonemic Awareness'},

  // ELA — Phonics
  {id:'K.10a',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Produce the most frequent sound(s) for each consonant, including x (/ks/) and q (/kw/).',
   code:'K.10.a',tag:'Phonics'},
  {id:'K.10b',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Identify the vowel in a closed syllable; produce short vowel sounds for the five major vowels.',
   code:'K.10.b',tag:'Phonics'},
  {id:'K.10c',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Decode consonant-vowel-consonant (CVC) words in isolation and in decodable text.',
   code:'K.10.c',tag:'Phonics'},

  // ELA — Fluency / Letters
  {id:'K.11',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Recognize and name all uppercase and lowercase letters in non-sequential order with accuracy.',
   code:'K.11',tag:'Fluency'},
  {id:'K.12',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Arrange and name letters of the alphabet in sequential order from A to Z.',
   code:'K.12',tag:'Fluency'},
  {id:'K.16',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Recognize and read grade-appropriate high-frequency sight words with accuracy and automaticity.',
   code:'K.16',tag:'Sight Words'},

  // ELA — Comprehension
  {id:'K.27a',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Retell a story orally, including main character(s), setting, and important events in logical order.',
   code:'K.27.a',tag:'Comprehension'},
  {id:'K.29',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Identify the main topic and key details in an informational text with prompting and support.',
   code:'K.29',tag:'Comprehension'},

  // ELA — Writing
  {id:'K.34a',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Print uppercase and lowercase letters using proper approach strokes, letter formation, and line placement.',
   code:'K.34.a',tag:'Handwriting'},
  {id:'K.34b',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Print first and last name using proper letter formation, capitalizing only the first letter of each name.',
   code:'K.34.b',tag:'Writing'},
  {id:'K.36e',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Begin sentences with a capital letter.',
   code:'K.36.e',tag:'Writing'},
  {id:'K.36g',grade:'K',subject:'Language Arts',icon:'📖',
   text:'Recognize, name, and correctly use end punctuation: period and question mark.',
   code:'K.36.g',tag:'Writing'},

  // MATH — Foundations of Counting
  {id:'K.M1',grade:'K',subject:'Mathematics',icon:'🔢',
   text:'Count forward orally from 0 to 100 by ones and by tens; count backward from 10 to 0 by ones.',
   code:'K.1 (Math)',tag:'Counting'},
  {id:'K.M2',grade:'K',subject:'Mathematics',icon:'🔢',
   text:'Count to 100 by ones beginning with any given number between 0 and 99.',
   code:'K.2',tag:'Counting'},
  {id:'K.M3',grade:'K',subject:'Mathematics',icon:'🔢',
   text:'Write numerals from 0 to 20 and represent quantities 0–20 with concrete objects.',
   code:'K.3',tag:'Number Recognition'},
  {id:'K.M4',grade:'K',subject:'Mathematics',icon:'🔢',
   text:'Connect counting to cardinality — the last number said tells "how many"; count objects in a set.',
   code:'K.4',tag:'Counting & Cardinality'},
  {id:'K.M6',grade:'K',subject:'Mathematics',icon:'🔢',
   text:'Compare two groups of objects and identify which is greater than, less than, or equal to the other.',
   code:'K.6',tag:'Comparison'},
  {id:'K.M7',grade:'K',subject:'Mathematics',icon:'🔢',
   text:'Compare two numerals between 1 and 10 using "greater than," "less than," or "equal to."',
   code:'K.7',tag:'Comparison'},
  {id:'K.M8',grade:'K',subject:'Mathematics',icon:'🔢',
   text:'Represent addition and subtraction within 10 using objects, fingers, drawings, and equations.',
   code:'K.8 (Math)',tag:'Operations'},
  {id:'K.M10',grade:'K',subject:'Mathematics',icon:'🔢',
   text:'Fluently add and subtract within 5.',
   code:'K.10 (Math)',tag:'Operations'},
  {id:'K.M14',grade:'K',subject:'Mathematics',icon:'🔢',
   text:'Identify, name, and describe 2D shapes (circle, square, triangle, rectangle, hexagon) and 3D shapes (cube, cone, cylinder, sphere).',
   code:'K.14–15',tag:'Geometry'},
  {id:'K.M17',grade:'K',subject:'Mathematics',icon:'🔢',
   text:'Sort objects into given categories by count; compare category counts.',
   code:'K.17 (Math)',tag:'Data & Sorting'},

  // ═══ FIRST GRADE ═══

  // 1st ELA — Phonological / Phonics
  {id:'1.1',grade:'1',subject:'Language Arts',icon:'📖',
   text:'Distinguish long and short vowel sounds when reading regularly spelled one-syllable words.',
   code:'1.10.a',tag:'Phonics'},
  {id:'1.2',grade:'1',subject:'Language Arts',icon:'📖',
   text:'Decode two-syllable words by breaking them into syllables using common syllabication patterns.',
   code:'1.10.d',tag:'Phonics'},
  {id:'1.3',grade:'1',subject:'Language Arts',icon:'📖',
   text:'Read words with common prefixes and suffixes (e.g., re-, un-, -ed, -ing, -er, -est).',
   code:'1.10.e',tag:'Word Analysis'},
  {id:'1.4',grade:'1',subject:'Language Arts',icon:'📖',
   text:'Recognize and read grade-appropriate irregular high-frequency words (e.g., said, was, are, they, from).',
   code:'1.16',tag:'Sight Words'},
  {id:'1.5',grade:'1',subject:'Language Arts',icon:'📖',
   text:'Orally read grade-level text with sufficient accuracy and fluency to support comprehension.',
   code:'1.15',tag:'Fluency'},

  // 1st ELA — Comprehension
  {id:'1.6',grade:'1',subject:'Language Arts',icon:'📖',
   text:'Retell stories including key details; demonstrate understanding of the central message or lesson.',
   code:'1.27',tag:'Comprehension'},
  {id:'1.7',grade:'1',subject:'Language Arts',icon:'📖',
   text:'Ask and answer questions about key details in a text; refer to the text for support.',
   code:'1.30',tag:'Comprehension'},
  {id:'1.8',grade:'1',subject:'Language Arts',icon:'📖',
   text:'Describe characters, settings, and major events in a story, using key details.',
   code:'1.27.b',tag:'Comprehension'},
  {id:'1.9',grade:'1',subject:'Language Arts',icon:'📖',
   text:'Identify the main topic and retell key details of an informational text.',
   code:'1.29',tag:'Comprehension'},

  // 1st ELA — Writing
  {id:'1.10',grade:'1',subject:'Language Arts',icon:'📖',
   text:'Write complete sentences with a capital letter at the beginning and correct end punctuation.',
   code:'1.36',tag:'Writing'},
  {id:'1.11',grade:'1',subject:'Language Arts',icon:'📖',
   text:'Use common nouns, proper nouns, and verbs correctly in written sentences.',
   code:'1.36.c',tag:'Grammar'},
  {id:'1.12',grade:'1',subject:'Language Arts',icon:'📖',
   text:'Write narratives recounting two or more appropriately sequenced events with a closure.',
   code:'1.37.b',tag:'Writing'},
  {id:'1.13',grade:'1',subject:'Language Arts',icon:'📖',
   text:'Write opinion pieces that introduce a topic, state an opinion, supply a reason, and provide closure.',
   code:'1.37.c',tag:'Writing'},

  // 1st Math
  {id:'1.M1',grade:'1',subject:'Mathematics',icon:'🔢',
   text:'Use properties of addition (commutative and associative) to add and subtract within 20; demonstrate fluency for addition/subtraction within 10.',
   code:'1.1–1.3 (Math)',tag:'Operations'},
  {id:'1.M2',grade:'1',subject:'Mathematics',icon:'🔢',
   text:'Solve word problems involving addition and subtraction within 20 using objects, drawings, and equations.',
   code:'1.1 (Math)',tag:'Operations'},
  {id:'1.M3',grade:'1',subject:'Mathematics',icon:'🔢',
   text:'Count to 120, starting at any number less than 120; read and write numerals to 120.',
   code:'1.8 (Math)',tag:'Number & Place Value'},
  {id:'1.M4',grade:'1',subject:'Mathematics',icon:'🔢',
   text:'Understand two-digit numbers represent tens and ones; compare two two-digit numbers using >, =, <.',
   code:'1.9–1.11',tag:'Place Value'},
  {id:'1.M5',grade:'1',subject:'Mathematics',icon:'🔢',
   text:'Add within 100, including adding a two-digit number and a one-digit number, using concrete models.',
   code:'1.12',tag:'Operations'},
  {id:'1.M6',grade:'1',subject:'Mathematics',icon:'🔢',
   text:'Order three objects by length; compare the lengths of two objects using a third object as a referent.',
   code:'1.16 (Math)',tag:'Measurement'},
  {id:'1.M7',grade:'1',subject:'Mathematics',icon:'🔢',
   text:'Tell and write time in hours and half-hours using analog and digital clocks.',
   code:'1.18 (Math)',tag:'Time'},
  {id:'1.M8',grade:'1',subject:'Mathematics',icon:'🔢',
   text:'Partition circles and rectangles into two and four equal shares using the words halves and fourths.',
   code:'1.22 (Math)',tag:'Geometry / Fractions'},

  // ═══ SECOND GRADE ═══

  // 2nd ELA — Phonics
  {id:'2.1',grade:'2',subject:'Language Arts',icon:'📖',
   text:'Know and apply grade-level phonics — long and short vowels, vowel teams, r-controlled vowels, and common suffixes.',
   code:'2.10',tag:'Phonics'},
  {id:'2.2',grade:'2',subject:'Language Arts',icon:'📖',
   text:'Read multisyllabic words by applying knowledge of syllabication patterns accurately.',
   code:'2.10.d',tag:'Word Analysis'},
  {id:'2.3',grade:'2',subject:'Language Arts',icon:'📖',
   text:'Read grade-appropriate irregularly spelled words and 200+ high-frequency sight words with automaticity.',
   code:'2.16',tag:'Sight Words'},
  {id:'2.4',grade:'2',subject:'Language Arts',icon:'📖',
   text:'Read grade-level prose and poetry orally with accuracy, appropriate rate, and expression on successive readings.',
   code:'2.15',tag:'Fluency'},

  // 2nd ELA — Comprehension
  {id:'2.5',grade:'2',subject:'Language Arts',icon:'📖',
   text:'Recount stories and fables; determine their central message, lesson, or moral.',
   code:'2.27',tag:'Comprehension'},
  {id:'2.6',grade:'2',subject:'Language Arts',icon:'📖',
   text:'Ask and answer such questions as who, what, where, when, why, and how to demonstrate understanding of key details in a text.',
   code:'2.30',tag:'Comprehension'},
  {id:'2.7',grade:'2',subject:'Language Arts',icon:'📖',
   text:'Identify the main purpose of an informational text, including what the author wants to explain or describe.',
   code:'2.29',tag:'Comprehension'},
  {id:'2.8',grade:'2',subject:'Language Arts',icon:'📖',
   text:'Compare and contrast two or more versions of the same story by different authors or from different cultures.',
   code:'2.32',tag:'Comprehension'},

  // 2nd ELA — Writing / Grammar
  {id:'2.9',grade:'2',subject:'Language Arts',icon:'📖',
   text:'Write narratives that include a well-elaborated event or short sequence of events, with descriptive details and a closure.',
   code:'2.37.b',tag:'Writing'},
  {id:'2.10',grade:'2',subject:'Language Arts',icon:'📖',
   text:'Write opinion pieces identifying a topic, stating an opinion, supplying reasons that support the opinion, using linking words (because, and, also), and providing a concluding statement.',
   code:'2.37.c',tag:'Writing'},
  {id:'2.11',grade:'2',subject:'Language Arts',icon:'📖',
   text:'Use collective nouns, irregular plural nouns, reflexive pronouns, and past-tense irregular verbs correctly.',
   code:'2.36.c–d',tag:'Grammar'},
  {id:'2.12',grade:'2',subject:'Language Arts',icon:'📖',
   text:'Use commas in greetings and closings of letters; use an apostrophe to form contractions and possessives.',
   code:'2.36.h–i',tag:'Punctuation'},

  // 2nd Math
  {id:'2.M1',grade:'2',subject:'Mathematics',icon:'🔢',
   text:'Fluently add and subtract within 20 using mental strategies; know all sums of two one-digit numbers from memory.',
   code:'2.1 (Math)',tag:'Operations'},
  {id:'2.M2',grade:'2',subject:'Mathematics',icon:'🔢',
   text:'Solve one- and two-step word problems involving addition and subtraction within 100.',
   code:'2.2 (Math)',tag:'Operations'},
  {id:'2.M3',grade:'2',subject:'Mathematics',icon:'🔢',
   text:'Understand that the three digits of a three-digit number represent hundreds, tens, and ones; count within 1000.',
   code:'2.7–2.8 (Math)',tag:'Place Value'},
  {id:'2.M4',grade:'2',subject:'Mathematics',icon:'🔢',
   text:'Fluently add and subtract within 100 using strategies based on place value and properties of operations.',
   code:'2.9 (Math)',tag:'Operations'},
  {id:'2.M5',grade:'2',subject:'Mathematics',icon:'🔢',
   text:'Add up to four two-digit numbers using strategies based on place value and properties of operations.',
   code:'2.10 (Math)',tag:'Operations'},
  {id:'2.M6',grade:'2',subject:'Mathematics',icon:'🔢',
   text:'Measure the length of an object in standard units (inches, feet, centimeters, meters); relate addition and subtraction to length.',
   code:'2.14–2.15 (Math)',tag:'Measurement'},
  {id:'2.M7',grade:'2',subject:'Mathematics',icon:'🔢',
   text:'Tell and write time from analog and digital clocks to the nearest five minutes, using a.m. and p.m.',
   code:'2.17 (Math)',tag:'Time'},
  {id:'2.M8',grade:'2',subject:'Mathematics',icon:'🔢',
   text:'Solve word problems involving dollar bills, quarters, dimes, nickels, and pennies using $ and ¢ symbols.',
   code:'2.18 (Math)',tag:'Money'},
  {id:'2.M9',grade:'2',subject:'Mathematics',icon:'🔢',
   text:'Draw a picture graph and bar graph to represent data; solve problems using information in the graphs.',
   code:'2.19 (Math)',tag:'Data'},
  {id:'2.M10',grade:'2',subject:'Mathematics',icon:'🔢',
   text:'Recognize and draw shapes with specified attributes (triangles, quadrilaterals, pentagons, hexagons); partition shapes into equal shares (halves, thirds, fourths).',
   code:'2.21–2.22 (Math)',tag:'Geometry'},

  // ═══ MOTOR SKILLS — KINDERGARTEN ═══
  {id:'K.FM1',grade:'K',subject:'Motor Skills',icon:'✍️',
   text:'Holds a pencil or crayon with a proper tripod grasp (thumb and two fingers).',
   code:'Fine Motor',tag:'Fine Motor'},
  {id:'K.FM2',grade:'K',subject:'Motor Skills',icon:'✍️',
   text:'Cuts along a straight line and simple curved line with child-sized scissors.',
   code:'Fine Motor',tag:'Fine Motor'},
  {id:'K.FM3',grade:'K',subject:'Motor Skills',icon:'✍️',
   text:'Copies basic pre-writing shapes: vertical line, horizontal line, circle, cross, and square.',
   code:'Fine Motor',tag:'Pre-Writing'},
  {id:'K.FM4',grade:'K',subject:'Motor Skills',icon:'✍️',
   text:'Colors mostly within the lines of a simple drawing.',
   code:'Fine Motor',tag:'Fine Motor'},
  {id:'K.FM5',grade:'K',subject:'Motor Skills',icon:'✍️',
   text:'Draws a recognizable person with at least four body parts (head, body, arms, legs).',
   code:'Fine Motor',tag:'Drawing'},
  {id:'K.GM1',grade:'K',subject:'Motor Skills',icon:'✍️',
   text:'Hops on one foot at least five times without losing balance.',
   code:'Gross Motor',tag:'Gross Motor'},
  {id:'K.GM2',grade:'K',subject:'Motor Skills',icon:'✍️',
   text:'Skips with alternating feet in a coordinated pattern.',
   code:'Gross Motor',tag:'Gross Motor'},
  {id:'K.GM3',grade:'K',subject:'Motor Skills',icon:'✍️',
   text:'Catches a large ball thrown from a short distance with both hands.',
   code:'Gross Motor',tag:'Gross Motor'},
  {id:'K.GM4',grade:'K',subject:'Motor Skills',icon:'✍️',
   text:'Climbs playground equipment with confidence; uses balance beam with minimal support.',
   code:'Gross Motor',tag:'Gross Motor'},

  // ═══ MOTOR SKILLS — 1ST GRADE ═══
  {id:'1.FM1',grade:'1',subject:'Motor Skills',icon:'✍️',
   text:'Prints all uppercase and lowercase letters legibly with consistent size and spacing.',
   code:'Fine Motor',tag:'Handwriting'},
  {id:'1.FM2',grade:'1',subject:'Motor Skills',icon:'✍️',
   text:'Cuts out simple shapes (circle, square, triangle) following the outline with scissors.',
   code:'Fine Motor',tag:'Fine Motor'},
  {id:'1.FM3',grade:'1',subject:'Motor Skills',icon:'✍️',
   text:'Copies a triangle and diamond shape; draws pictures with recognizable details.',
   code:'Fine Motor',tag:'Pre-Writing'},
  {id:'1.FM4',grade:'1',subject:'Motor Skills',icon:'✍️',
   text:'Ties shoelaces independently using a two-loop method.',
   code:'Fine Motor',tag:'Self-Care'},
  {id:'1.FM5',grade:'1',subject:'Motor Skills',icon:'✍️',
   text:'Manipulates small objects with control: beads, buttons, zippers, and puzzle pieces.',
   code:'Fine Motor',tag:'Fine Motor'},
  {id:'1.GM1',grade:'1',subject:'Motor Skills',icon:'✍️',
   text:'Skips, gallops, and hops with coordination and rhythm.',
   code:'Gross Motor',tag:'Gross Motor'},
  {id:'1.GM2',grade:'1',subject:'Motor Skills',icon:'✍️',
   text:'Rides a bike with training wheels or balance bike with confidence.',
   code:'Gross Motor',tag:'Gross Motor'},
  {id:'1.GM3',grade:'1',subject:'Motor Skills',icon:'✍️',
   text:'Throws a ball overhand with direction; kicks a moving ball accurately.',
   code:'Gross Motor',tag:'Gross Motor'},

  // ═══ MOTOR SKILLS — 2ND GRADE ═══
  {id:'2.FM1',grade:'2',subject:'Motor Skills',icon:'✍️',
   text:'Writes in print with consistent size, spacing, and letter formation; begins to form cursive letters (if introduced).',
   code:'Fine Motor',tag:'Handwriting'},
  {id:'2.FM2',grade:'2',subject:'Motor Skills',icon:'✍️',
   text:'Cuts out complex shapes with curved and angled lines accurately.',
   code:'Fine Motor',tag:'Fine Motor'},
  {id:'2.FM3',grade:'2',subject:'Motor Skills',icon:'✍️',
   text:'Uses ruler, pencil, and basic tools to draw measured lines and shapes.',
   code:'Fine Motor',tag:'Fine Motor'},
  {id:'2.FM4',grade:'2',subject:'Motor Skills',icon:'✍️',
   text:'Demonstrates fluid, coordinated hand-eye tasks: threading a needle, folding paper precisely.',
   code:'Fine Motor',tag:'Fine Motor'},
  {id:'2.GM1',grade:'2',subject:'Motor Skills',icon:'✍️',
   text:'Rides a bike without training wheels; navigates turns and stops safely.',
   code:'Gross Motor',tag:'Gross Motor'},
  {id:'2.GM2',grade:'2',subject:'Motor Skills',icon:'✍️',
   text:'Jumps rope with coordination; participates in organized physical games with rule-following.',
   code:'Gross Motor',tag:'Gross Motor'},
  {id:'2.GM3',grade:'2',subject:'Motor Skills',icon:'✍️',
   text:'Demonstrates balance: walks a balance beam forward and backward; stands on one foot 10+ seconds.',
   code:'Gross Motor',tag:'Gross Motor'},

  // ═══ SOCIAL / EMOTIONAL — KINDERGARTEN ═══
  {id:'K.SE1',grade:'K',subject:'Social & Emotional',icon:'🤝',
   text:'Follows two-step directions without reminders in a learning setting.',
   code:'Self-Regulation',tag:'Attention'},
  {id:'K.SE2',grade:'K',subject:'Social & Emotional',icon:'🤝',
   text:'Expresses feelings using words (happy, sad, frustrated, excited) rather than acting out.',
   code:'Social-Emotional',tag:'Emotional Literacy'},
  {id:'K.SE3',grade:'K',subject:'Social & Emotional',icon:'🤝',
   text:'Shares materials and takes turns with peers during play or group activities.',
   code:'Social-Emotional',tag:'Social Skills'},
  {id:'K.SE4',grade:'K',subject:'Social & Emotional',icon:'🤝',
   text:'Separates from parent or caregiver without significant distress.',
   code:'Social-Emotional',tag:'Independence'},
  {id:'K.SE5',grade:'K',subject:'Social & Emotional',icon:'🤝',
   text:'Sits and attends to a structured activity or lesson for 10–15 minutes.',
   code:'Self-Regulation',tag:'Focus'},
  {id:'K.SE6',grade:'K',subject:'Social & Emotional',icon:'🤝',
   text:'Shows empathy — notices when someone is upset and responds with kindness.',
   code:'Social-Emotional',tag:'Empathy'},
  {id:'K.SE7',grade:'K',subject:'Social & Emotional',icon:'🤝',
   text:'Completes a simple task or project independently from start to finish.',
   code:'Self-Regulation',tag:'Independence'},
  {id:'K.SE8',grade:'K',subject:'Social & Emotional',icon:'🤝',
   text:'Handles disappointment or frustration without a major meltdown; uses a calming strategy.',
   code:'Self-Regulation',tag:'Emotional Regulation'},

  // ═══ SOCIAL / EMOTIONAL — 1ST GRADE ═══
  {id:'1.SE1',grade:'1',subject:'Social & Emotional',icon:'🤝',
   text:'Follows multi-step classroom routines independently (e.g., unpack, begin morning work, transition to subjects).',
   code:'Self-Regulation',tag:'Independence'},
  {id:'1.SE2',grade:'1',subject:'Social & Emotional',icon:'🤝',
   text:'Resolves minor peer conflicts using words — asks for help or negotiates rather than reacting physically.',
   code:'Social-Emotional',tag:'Conflict Resolution'},
  {id:'1.SE3',grade:'1',subject:'Social & Emotional',icon:'🤝',
   text:'Identifies and names a range of emotions (nervous, proud, embarrassed, calm) in self and others.',
   code:'Social-Emotional',tag:'Emotional Literacy'},
  {id:'1.SE4',grade:'1',subject:'Social & Emotional',icon:'🤝',
   text:'Stays on task during independent work for 15–20 minutes with minimal redirection.',
   code:'Self-Regulation',tag:'Focus'},
  {id:'1.SE5',grade:'1',subject:'Social & Emotional',icon:'🤝',
   text:'Works cooperatively in a small group — contributes ideas, listens to others, shares materials.',
   code:'Social-Emotional',tag:'Teamwork'},
  {id:'1.SE6',grade:'1',subject:'Social & Emotional',icon:'🤝',
   text:'Accepts corrective feedback from a teacher or parent without shutting down or becoming defiant.',
   code:'Self-Regulation',tag:'Growth Mindset'},

  // ═══ SOCIAL / EMOTIONAL — 2ND GRADE ═══
  {id:'2.SE1',grade:'2',subject:'Social & Emotional',icon:'🤝',
   text:'Manages transitions between subjects or activities smoothly without significant anxiety.',
   code:'Self-Regulation',tag:'Flexibility'},
  {id:'2.SE2',grade:'2',subject:'Social & Emotional',icon:'🤝',
   text:'Demonstrates perseverance on challenging tasks — tries multiple approaches before asking for help.',
   code:'Self-Regulation',tag:'Growth Mindset'},
  {id:'2.SE3',grade:'2',subject:'Social & Emotional',icon:'🤝',
   text:'Understands the concept of fairness and applies it in games and group settings.',
   code:'Social-Emotional',tag:'Social Skills'},
  {id:'2.SE4',grade:'2',subject:'Social & Emotional',icon:'🤝',
   text:'Distinguishes between tattling and reporting a genuine safety concern.',
   code:'Social-Emotional',tag:'Social Awareness'},
  {id:'2.SE5',grade:'2',subject:'Social & Emotional',icon:'🤝',
   text:'Sets and pursues a simple personal goal (e.g., "I want to read one chapter book this week").',
   code:'Self-Regulation',tag:'Goal Setting'},
  {id:'2.SE6',grade:'2',subject:'Social & Emotional',icon:'🤝',
   text:'Sustains focused attention for 20–25 minutes during structured learning without prompting.',
   code:'Self-Regulation',tag:'Focus'},
];
